In [1]:
x=[1,2,3,4,5]
y=[2,4,5,6,7]

In [6]:
x+y

[1, 2, 3, 4, 5, 2, 4, 5, 6, 7]

In [7]:
type(x)

list

In [3]:
import numpy as np

In [4]:
a=np.array(x)
b=np.array(y)

In [5]:
type(a)

numpy.ndarray

In [8]:
a+b

array([ 3,  6,  8, 10, 12])

In [9]:
a.size

5

In [10]:
b.shape

(5,)

In [11]:
np.array([[2,4],[3,4]])

array([[2, 4],
       [3, 4]])

In [13]:
x=np.array([[2,4],[3,4]])
y=np.array([[1,2],[6,5]])
x+y

array([[3, 6],
       [9, 9]])

In [14]:
x*y

array([[ 2,  8],
       [18, 20]])

In [12]:
x>y

array([[ True,  True],
       [False, False]])

In [13]:
x.dot(y)

array([[26, 24],
       [27, 26]])

In [14]:
np.cross(x,y)

array([ 0, -9])

In [15]:
np.sum(x)

13

In [15]:
np.mean(x)

3.25

In [16]:
z1=[1,2,3,4]
z2=[2,3,4,5]
z=np.array([z1,z2])
z.shape

(2, 4)

In [18]:
z.cumsum()

array([ 1,  3,  6, 10, 12, 15, 19, 24], dtype=int32)

In [19]:
z.cumprod()

array([   1,    2,    6,   24,   48,  144,  576, 2880], dtype=int32)

In [20]:
z.max()

5

In [21]:
z.min()

1

In [22]:
z.sum()

24

In [23]:
z.std()

1.224744871391589

In [24]:
z.transpose()

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [25]:
z.T

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [26]:
np.arange(1,10,.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [27]:
data=np.arange(1,10,.2)
data.shape

(45,)

In [28]:
data.reshape((5,9))

array([[1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6],
       [2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4],
       [4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2],
       [6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ],
       [8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [29]:
data.reshape((9,5))

array([[1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8],
       [3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8],
       [5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8],
       [7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8],
       [9. , 9.2, 9.4, 9.6, 9.8]])

In [30]:
data.reshape((5,3,3))

array([[[1. , 1.2, 1.4],
        [1.6, 1.8, 2. ],
        [2.2, 2.4, 2.6]],

       [[2.8, 3. , 3.2],
        [3.4, 3.6, 3.8],
        [4. , 4.2, 4.4]],

       [[4.6, 4.8, 5. ],
        [5.2, 5.4, 5.6],
        [5.8, 6. , 6.2]],

       [[6.4, 6.6, 6.8],
        [7. , 7.2, 7.4],
        [7.6, 7.8, 8. ]],

       [[8.2, 8.4, 8.6],
        [8.8, 9. , 9.2],
        [9.4, 9.6, 9.8]]])

In [31]:
data.reshape((15,3))

array([[1. , 1.2, 1.4],
       [1.6, 1.8, 2. ],
       [2.2, 2.4, 2.6],
       [2.8, 3. , 3.2],
       [3.4, 3.6, 3.8],
       [4. , 4.2, 4.4],
       [4.6, 4.8, 5. ],
       [5.2, 5.4, 5.6],
       [5.8, 6. , 6.2],
       [6.4, 6.6, 6.8],
       [7. , 7.2, 7.4],
       [7.6, 7.8, 8. ],
       [8.2, 8.4, 8.6],
       [8.8, 9. , 9.2],
       [9.4, 9.6, 9.8]])

In [32]:
datax=np.linspace(1,10,100)
datax

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [33]:
datar=np.random.rand(4,3)
datar

array([[0.69502485, 0.66110624, 0.73371341],
       [0.94177441, 0.50687228, 0.80632378],
       [0.67432116, 0.28344547, 0.11195099],
       [0.34164524, 0.45759484, 0.76057008]])

In [34]:
dataz=np.random.randint(1,11,(3,5))
dataz

array([[ 3, 10,  6,  4, 10],
       [ 5,  5,  6,  8,  8],
       [ 3,  2,  3,  4, 10]])

In [35]:
np.ones(shape=4)

array([1., 1., 1., 1.])

In [17]:
np.zeros(shape=43)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
datar.shape

(4, 3)

In [40]:
dataz.shape

(3, 5)

In [19]:
x=np.random.randint(1,10,(2,2))
y=np.random.randint(1,10,(2,2))
print(x)
print(y)

[[8 7]
 [9 5]]
[[2 7]
 [6 6]]


In [20]:
np.append(x,y,axis=1)

array([[8, 7, 2, 7],
       [9, 5, 6, 6]])

In [43]:
np.append(x,y,axis=0)

array([[8, 2],
       [8, 1],
       [3, 6],
       [1, 8]])

In [44]:
x=[[1,2,3,4,5,6],
  [1,2,3,4,5,6],
  [1,2,3,4,5,6],
  [1,2,3,4,5,6],
  [1,2,3,4,5,6],
  [1,2,3,4,5,6],]

In [21]:
s=np.random.randint(1,10,(6,6))
s

array([[8, 4, 6, 9, 2, 8],
       [5, 3, 2, 2, 4, 2],
       [6, 2, 1, 1, 5, 8],
       [5, 7, 9, 1, 3, 5],
       [9, 8, 5, 1, 1, 7],
       [6, 4, 9, 9, 6, 7]])

In [22]:
s[4:,:]

array([[9, 8, 5, 1, 1, 7],
       [6, 4, 9, 9, 6, 7]])

In [24]:
s[2:4,3:]

array([[1, 5, 8],
       [1, 3, 5]])